### ISSUE TITLE
Bug: There seems to be a conflict between sbt and the new Dockerfile

### ISSUE THREAD

**Issue by cswen17** [cswen17/cgq-streaming-greedy#9]
Can't develop project locally anymore/dev is broken.

shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Copying runtime jar.
mkdir: : No such file or directory
Error occurred during initialization of VM
java.lang.Error: Properties init: Could not determine current working directory.
	at java.lang.System.initProperties(Native Method)
	at java.lang.System.initializeSystemClass(System.java:1166)

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Error occurred during initialization of VM
java.lang.Error: Properties init: Could not determine current working directory.
	at java.lang.System.initProperties(Native Method)
	at java.lang.System.initializeSystemClass(System.java:1166)

**Comment by cswen17** [comment]
Will move Dockerfile to its own directory, e.g. cgq-streaminig-greedy/docker/
